version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR Public...
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/u9j3n1n7
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/767397745665/capstone/backend-app:latest .
      - docker tag public.ecr.aws/767397745665/capstone/backend-app:latest public.ecr.aws/767397745665/capstone/backend-app:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/767397745665/capstone/backend-app:latest
      - echo Verifying image push...
      - aws ecr-public describe-images --repository-name capstone/backend-app --registry-id 767397745665
      - printf '[{"name":"backend-container","imageUri":"%s"}]' public.ecr.aws/767397745665/capstone/backend-app:latest > imagedefinitions.json
